#!/bin/bash
##Alexandre D'Amato
#export TERM=vt100
export TERM=xterm
export ESTILO1=big
export ESTILO2=slant
export ESTILO3=big
export programa=$0
export HORA=$(date +"%Y-%m-%d_%H-%M_%S")
export LOGPATH=/home/damato/Documents/ssh
export dirtmp=/tmp
export ultimamaquina=.ns
export ultimasessao=.nss
export CMD_FIGLET=/usr/bin/figlet
export CMD_ECHO=/bin/echo
export CMD_AWK=/usr/bin/awk
export CMD_MKTEMP=/bin/mktemp
export CMD_WC=/usr/bin/wc
export CMD_GREP=/bin/grep
export CMD_SORT=/usr/bin/sort
export CMD_CAT=/bin/cat
export CMD_TEE=/usr/bin/tee
export CMD_SCREEN=/usr/bin/screen
export CMD_SSH=/usr/bin/ssh
export CMD_RM=/bin/rm
export CMD_CLEAR=/usr/bin/clear
export CMD_PING=/bin/ping
export CMD_SLEEP=/bin/sleep
#export BASE_DADOS=/etc/hosts
function Tempfunc() {
	case $1 in
	criar)
		$CMD_MKTEMP -p /tmp --suffix ssh-netshoe
		;;
	apagar)
		$CMD_RM -f $2
		;;
	*)
		echo erro
		exit 1
		;;
	esac
}
function Pingar() {
	$CMD_PING -c 1 $1 > /dev/null
	retorno=$?
	if [[ $retorno -eq 0 ]]
	then
		$CMD_FIGLET -f $ESTILO3 ON-LINE
	else
		$CMD_FIGLET -f $ESTILO3 OFF-LINE
		$CMD_FIGLET -f $ESTILO1 $1
		$CMD_GREP $1 /etc/hosts
		#$CMD_SLEEP 4
		#exit 1	
	fi
}
function Escolha_usuario() {
	UNITARIO=1
	USUARIO=$($CMD_ECHO $1 | $CMD_AWK -F @ '{print $1}')
	case $USUARIO in
	a)
	        export USUARIO=adm.alexandre.gomes
	        ;;
	r)
	        export USUARIO=root
	        ;;
	o)
	        export USUARIO=operador
	        ;;
	esac
}
function menu() {

case $# in
	1)
		$STRING_C=$1
		MAQUINA=$($CMD_ECHO $STRING_C| $CMD_AWK -F @ '{print $2}')
		#TMPFILE=$($CMD_MKTEMP -p /tmp --suffix ssh-netshoes)
		TMPFILE=$(Tempfunc criar)
		BASE_DADOS=/etc/hosts
		$CMD_GREP -i $MAQUINA $BASE_DADOS |$CMD_GREP -v ^\#|$CMD_SORT -k2| $CMD_CAT -n |$CMD_AWK '{print $1" "$3" "$2}' > $TMPFILE
		;;
	2)
		MAQUINA=$1
		BASE_DADOS=$2
		TMPFILE=$(Tempfunc criar)
		$CMD_GREP -i $MAQUINA $BASE_DADOS |awk '{print $2 " " $3}' |$CMD_CAT -n |$CMD_AWK '{print $1" "$3" "$2}' > $TMPFILE
		;;
	*)
		exit 1
		;;
esac

RETORNO=$($CMD_WC -l $TMPFILE|$CMD_AWK '{print $1}')
if [[ $RETORNO -eq $UNITARIO ]]
then
        export SERVIDOR=$($CMD_CAT $TMPFILE |$CMD_AWK '{print $2}')
	$CMD_SCREEN -t $USUARIO@$SERVIDOR $programa $USUARIO $SERVIDOR
	$CMD_ECHO $SERVIDOR > $dirtmp/$ultimamaquina
	$CMD_ECHO $USUARIO $SERVIDOR > $dirtmp/$ultimasessao
else
	$CMD_CLEAR
	while read line
	do
		$CMD_ECHO -e "\e[100;40m$line"
		read line
		$CMD_ECHO -e "\e[100;48m$line"
	done < $TMPFILE
	$CMD_ECHO -e "\e[45m$line"
	$CMD_ECHO \(u\)ltima = $($CMD_CAT $dirtmp/$ultimamaquina)
	$CMD_ECHO -e "\e[41m$line"
	$CMD_ECHO \(m\)aquina = $MAQUINA
	$CMD_ECHO -en "\e[0m"
	$CMD_ECHO \(V\)arias maquinas
	$CMD_ECHO \(F\)iltrar lista
	#http://misc.flogisoft.com/bash/tip_colors_and_formatting
        $CMD_ECHO Entre com uma opcao:
        read ESCOLHA
	case $ESCOLHA in
		u)
			export SERVIDOR=$($CMD_CAT $dirtmp/$ultimamaquina)
			$CMD_SCREEN -t $USUARIO@$SERVIDOR $programa $USUARIO $SERVIDOR
			;;
		m)
			export SERVIDOR=$MAQUINA
			$CMD_ECHO $SERVIDOR > $dirtmp/$ultimamaquina
			$CMD_ECHO $USUARIO $SERVIDOR > $dirtmp/$ultimasessao
			$CMD_SCREEN -t $USUARIO@$SERVIDOR $programa $USUARIO $SERVIDOR
			;;
		v)
			$CMD_ECHO Entre comos numeros das sessoes separado por virgula sem espaço
			varias_maquinas=""
			read varias_maquinas
			$CMD_ECHO $varias_maquinas | tr ',' '\n'| while read valor
			do
				export SERVIDOR=$($CMD_GREP -w ^$valor $TMPFILE |$CMD_AWK '{print $3}')
				export SSERVIDOR=$($CMD_GREP -w ^$valor $TMPFILE |$CMD_AWK '{print $2}')
				$CMD_SCREEN -t $USUARIO@$SSERVIDOR $programa $USUARIO $SERVIDOR	
			done
			;;
		f)
			read MAQUINA
			menu $MAQUINA $TMPFILE
			;;
		*)
        		export SERVIDOR=$($CMD_GREP -w ^$ESCOLHA $TMPFILE |$CMD_AWK '{print $3}')
			export SSERVIDOR=$($CMD_GREP -w ^$ESCOLHA $TMPFILE |$CMD_AWK '{print $2}')
			$CMD_ECHO $SERVIDOR > $dirtmp/$ultimamaquina
			$CMD_ECHO $USUARIO $SERVIDOR > $dirtmp/$ultimasessao
			$CMD_SCREEN -t $USUARIO@$SSERVIDOR $programa $USUARIO $SERVIDOR
			;;
	esac

fi
#$CMD_RM $TMPFILE
}
function Infinito() {
	while true
	do
		$CMD_CLEAR
		$CMD_FIGLET -f $ESTILO2 SSH MANAGER
		$CMD_ECHO \(U\)ltima sessao: $($CMD_CAT $dirtmp/$ultimasessao|tr ' ' '@')
		$CMD_ECHO Entre com sua string de conexao:
		read STRING_C
		if [[ $STRING_C == "" ]]
		then
			$CMD_CLEAR
			Infinito
		fi
		if [[ $STRING_C == "u" ]]
		then
			USUARIO=$(cat $dirtmp/$ultimasessao | awk '{print $1}')
			SERVIDOR=$(cat $dirtmp/$ultimasessao | awk '{print $2}')
			$CMD_SCREEN -t $USUARIO@$SERVIDOR $programa $USUARIO $SERVIDOR
		else
			Escolha_usuario $STRING_C
			menu $STRING_C
		fi	
	done
}
function conectar() {
	Pingar $2
        $CMD_FIGLET -f $ESTILO1 $2
        $CMD_SSH -XC -c blowfish-cbc,arcfour $1@$2 | $CMD_TEE -i $LOGPATH/$HORA.$2.log
}
case $# in
0)
	ssh-add -l | grep -w "/home/damato/.ssh/id_rsa" > /dev/null
	retorno=$?
	if [ $retorno -ne 0 ]
	then
		ssh-add
	fi
	$CMD_SCREEN -T $TERM -t GESTOR -S GESTOR $programa screen
	;;
1)
	case $1 in
	screen)
		Infinito
		;;
	term)
		echo \#1=vt100
		echo \#2=xterm
		echo \#3=xterm-256color
		echo \#4=screen
		read valor
		case $valor in
			1)
				export TERM=vt100
				;;
			2)
				export TERM=xterm
				;;
			3)
				export TERM=xterm-256color
				;;
			4)
				export TERM=screen
				;;
			*)
				exit 1
				;;
		esac
		$0 
		;;
	*)
		exit 1
		;;
	esac
	;;
2)
	conectar $1 $2
	;;
*)
	exit 1
	;;
esac
